
import HeroSection from '@/components/UI/HomePage/HeroSection/HeroSection';
import Gallery from '@/components/UI/HomePage/Gallery/Gallery';
import ZoomParallax from '@/components/UI/HomePage/ZoomParallax/ZoomParallax';
import Team from '@/components/UI/HomePage/Team/Team';
import Review from '@/components/UI/HomePage/Review/Review';
import Product from '@/components/UI/HomePage/Product/Product';
import Service from '@/components/UI/HomePage/Service/Service';
import FollowUsSection from '@/components/UI/HomePage/FollowUs/FollowUs';
import OurSpaces from '@/components/UI/HomePage/OurSpaces/OurSpaces';

export const metadata = {
  title: "Hannis Friseursalon",
  description: "Generated by create next app",
  other: {
    "og:url": "https://barber-shop-rho-eight.vercel.app/",
    "og:image": "https://i.ibb.co/nMhbngs/Screenshot-2024-06-15-000442.png"
  }
};

const HomePage = () => {

  return (
    <div>
      <HeroSection />
      <Service />
      <Product />
      <ZoomParallax />
      <Gallery />
      <OurSpaces />
      <Team />
      <Review />
      <FollowUsSection />
    </div>
  );
};

export default HomePage;